name: IoMBian builder

on: [push]

jobs:
    build:
      strategy:
        matrix:
          platform: [ubuntu-20.04]
      runs-on: ${{ matrix.platform }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Build IoMBian
          run:
            ./build-iombian.sh