name: IoMBian publisher

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install qemu-user-static
        run: sudo apt update && sudo apt install -y qemu-user-static
      - name: Build IoMBian
        run:
          ./build-iombian.sh
      - name: Rename file name with tag name
        run: mv deploy/*.zip iombian-${{ github.ref_name }}.zip
      - name: Publish the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'iombian-${{ github.ref_name }}.zip'